---
title: Sequoia Creative Lab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  alumni:
    title: alumni
    output: true
    permalink: "/:title/"
  jobs:
    title: jobs
    output: true
    permalink: "/:title/"
  logos:
    title: logos
    output: true
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: alumni
  values:
    layout: default
    title: 
    first_name: 
    last_name: 
    class: 
    company: 
    job_title: 
    dribbble: 
    linkedin: 
    email: 
    website: 
    github: 
- scope:
    path: ''
    type: logos
  values:
    layout: default
    title: 
    link: 
    class: 
    storylink: 
    delay: 
- scope:
    path: ''
    type: jobs
  values:
    layout: default
    job_title: 
    link: 
    company: 
    order: 
markdown: kramdown
theme: jekyll-theme-minimal
permalink: pretty
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- npm-debug.log
- gulpfile.js
